  # 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # gtag: Google 分析
  # comments: 文章评论系统
    # gitalk
    # disqus
  # navbar: 主题页面导航栏
  # catalog: 文章目录
  # prevnext: 文章末尾的上一页与下一页
  # friends: 友链
  # footer: 页脚信息
  # search: 文章搜索
  # colorSwitch: 深/浅配色切换
  # postShare: 文章分享
  # codeBlock: 代码块配置

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: https://img.tanglu.me/image.webp
  touch_icon: https://img.tanglu.me/image.webp

# 用户头像与昵称
avatar:
  author_photo: https://img.tanglu.me/image.webp
  author_nickname: tanglu
  path: /

# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: true
  gtagkey: G-X8CHQT28KM

# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: false
    appId: FP5iDHnhAB22BwHHA109y2Sg-MdYXbMMI
    appKey: T2bVelavTppevO939KvvxbYO
    placeholder: Welcome
    avatar: retro
    vempty_display: false
    serverURLs: https://fp5idhnh.api.lncldglobal.com

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，https-zxcxxxx-github-io即为shortname
    enable: false
    shortname: https-zxcxxxx-github-io
  
  # waline https://waline.js.org
  waline:
    enable: true
    serverURL: https://waline.tanglu.me



# 主题页面导航栏
navbar:
  -
    name: 主页
    enable: true
    path: /
    key: home
  -
    name: Archives
    enable: false
    path: /archives/
    key: archives
  -
    name: Categories
    enable: false
    path: /categories/
    key: categories
  -
    name: 标签
    enable: true
    path: /tags/
    key: tags

  -
    name: 事件
    enable: true
    path: /incidents/
    key: incidents
  -
    name: 友链
    enable: true
    path: /friends/
    key: friends
  -
    name: 关于我
    enable: true
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: hostloc
    site: https://hostloc.com
    meta: 全球主机交流论坛
  -
    nickname: nodeseek
    site: https://nodeseek.com
    meta: 喜欢Web开发，托管，vps /服务器和其他极客事物的人们的地方
  -
    nickname: v2ex
    site: https://v2ex.com
    meta: 创意工作者的社区。讨论编程、设计、硬件、游戏等令人激动的话题
  -
    nickname: LET
    site: https://lowendtalk.com
    meta: 国外主机交流
  -
    nickname: P3TERX
    site: https://p3terx.com
    meta: 目前主要分享站长个人在泛 IT 技术类知识中的学习与研究成果，多数为高质量原创教程类和科普类文章
  -
    nickname: 我不是咕咕鸽
    site: https://blog.laoda.de
    meta: 服务器折腾不完全指南，定期分享一些好玩的东西，不定期记录生活
  -
    nickname: Luminous
    site: https://luotianyi.vc
    meta: 记录生活中的点滴，留下回忆与怀恋
  -
    nickname: Rats
    site: https://www.moerats.com
    meta: 主要以VPS教程、程序搭建、脚本和资源分享为主
  -
    nickname: 阮一峰的网络日志
    site: https://www.ruanyifeng.com/blog/
    meta: 这里记录每周值得分享的科技内容，周五发布
  -
    nickname: Bajins
    site: https://www.bajins.com
    meta: 
  -
    nickname: Xhofe
    site: https://nn.ci
    meta: 开源项目alist的作者
  -
    nickname: 不死鸟
    site: https://iui.su
    meta: 每日分享
  -
    nickname: 庭说
    site: https://tingtalk.me
    meta: 
  -
    nickname: Suncle
    site: https://suncle.me
    meta: 
  -
    nickname: 猫猫博客
    site: https://catcat.blog
    meta: 
  -
    nickname: 秋水逸冰
    site: https://teddysun.com
    meta: 
  -
    nickname: 小小博客
    site: https://shagain.club
    meta: 
  -
    nickname: 肉肉的小宇宙
    site: https://rou.best
    meta: 
  -
    nickname: imazes
    site: https://kms.app
    meta: 
  -
    nickname: Hogwarts
    site: https://winamp.top
    meta: 
  -
    nickname: SunPma
    site: https://sunpma.com
    meta: 
  -
    nickname: 周先生
    site: https://mrchou.com
    meta: 
  -
    nickname: Hyper Tech
    site: https://haogeboke.com
    meta: 
  -
    nickname: 郭泽宇
    site: https://www.guozeyu.com
    meta: 发布的内容汇集以科技、摄影为主的原创精选文章、视频、图片、短文和 App 推荐
  -
    nickname: 代码如诗
    site: https://dgideas.net
    meta: 
  -
    nickname: MOE
    site: https://www.moe.ms
    meta: 一个Linux爱好者，平时捣腾Linux中所遇到的问题记录在此
  -
    nickname: 回声
    site: https://iecho.cc
    meta: 
  -
    nickname: 娃娃Code
    site: https://blog.dollcode.cn
    meta: 
  -
    nickname: Closure
    site: https://closure01.dev
    meta: 
  -
    nickname: bb的博客
    site: https://csicn.cn
    meta: 
  -
    nickname: 待添加...
    site: 
    meta: 


# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址

    # 按需取消注释以启用

      # name: github
      # icon: github
      # path: https://github.com/zchengsite/hexo-theme-oranges
    # -
    #   name: email
    #   icon: envelope
    #   path: 
    # -
    #   name: facebook
    #   icon: facebooksquare
    #   path:
    # -
    #   name: twitter
    #   icon: twitter
    #   path:
    # -
    #   name: wechat
    #   icon: wechat
    #   path:
    # -
    #   name: weibo
    #   icon: weibo
    #   path:

    #   # rss需安装 hexo-generator-feed 插件
    #   # 具体参照https://github.com/hexojs/hexo-generator-feed
    -
      name: rss
      icon: rss
      path: /atom.xml

  more:
    # 支持变量显示，可自定义扩展，具体见主题/layout/_partial/footer.ejs
    # 一般用来显示根据各种场景需要切换的文本，如时间年份
    # 如：{thisYear} 会被替换为今年年份

    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges

  # 浏览量统计
  # http://busuanzi.ibruce.info/
  views:
    enable: true
    provider: '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
    item:
      -
        enable: false
        id: busuanzi_value_site_pv
        name: 本站总访问量
        unit: 次
      -
        enable: true
        id: busuanzi_value_site_uv
        name: 
        unit: 访客
      -
        enable: true
        id: busuanzi_value_page_pv
        name: 
        unit: 阅读


# 文章搜索
search:
  enable: true
  placeholder: 

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true

# 代码块配置
codeBlock:
  # 代码块风格，默认normal
  # 可选：默认风格'normal'；mac黑色风格：'mac-black'
  style: 'mac-black'
  # 代码复制
  copy:
    enable: true

# MathJax Support
# 数学公式支持
mathjax:
  enable: true

# cdn配置，默认关闭，如需启动，先确保对应插件版本cdn资源可用后再开启
# 如资源加载失败，可替换cdn提供商或设置enable:false默认走本地资源
# 也可使用自己的cdn服务，资源在/theme/oranges/source/plugins下
cdns:
  jquery:
    enable: false
    url: https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js

  fancybox:
    enable: false
    url:
      css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
      js: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # LaTeX 公式
  mathjax:
    enable: false
    url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

  # 代码块复制
  clipboard:
    enable: false
    url: https://cdn.jsdelivr.net/npm/clipboard@2.0.10/dist/clipboard.min.js

  # 评论系统
  comments:
    gitalk:
      enable: false
      url:
        css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
        js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

    valine:
      enable: false
      url: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

    waline:
      enable: true
      url: 
        css: https://npm.elemecdn.com/@waline/client@2.15.5/dist/waline.css
        js: https://npm.elemecdn.com/@waline/client@2.15.5/dist/waline.mjs
themeColor: '#808080'
